package config

const (
	// PromNamespace specifies the namespace of the generated Prometheus metrics.
	PromNamespace = "finnhub"

	// SymbolLabel specifies the label name of the symbol label that should get
	// attached to all metrics generated by queries against the Finnhub API.
	SymbolLabel = "symbol"
)
