name: Test & build finnhub_exporter

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        run: make prepare
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          make lint
      - name: Test
        run: make test
  build-linux:
    needs: test
    runs-on: ubuntu-latest
    env:
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare
        run: make prepare
      - name: Build
        run: make build GOOS=$GOOS GOARCH=$GOARCH
